[package]
name = "docsql-server"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "docsql network server: SQL protocol + auth + replication"

[dependencies]
docsql-core = { path = "../docsql-core" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time"] }
serde.workspace = true
serde_json = "1"
aes-gcm = "0.10"
rand = "0.8"

[dev-dependencies]
tempfile.workspace = true
